### ISSUE TITLE
Some global styles are missing in `App.vue`

### ISSUE THREAD

**Issue by aseerkt** [johnkomarnicki/FireBlogs-YouTube#2]
Global styles added in the YouTube video is not updated in [`App.vue`]()

**Comment by mikekwabs** [comment]
Can't find the finished project

**Comment by aseerkt** [comment]
@mikekwabs Here you go [Final_source_code](https://github.com/johnkomarnicki/FireBlogs-YouTube/tree/Finished-Source-Code)
